name = "MetabolicEP_ToyImplementation"
uuid = "1c9bdb5a-e486-4dba-94dd-ca67fda50d19"
authors = ["josePereiro <jose.pereiro.lab@gmail.com> and contributors"]
version = "0.1.0"

[compat]
julia = "1.6"

[deps]
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
SpecialFunctions = "276daf66-3868-5448-9aa4-cd146d93841b"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
